### ISSUE TITLE
Why not `dispatchEvent`?

### ISSUE THREAD

**Issue by apipkin** [bendrucker/dom-event-target#1]
Just curious, why have a method called `send` instead of the `EventTarget`'s standard `dispatchEvent` method? I mean, granted, I could just do this in my code after the fact, just curious of the code design choice.

**Comment by apipkin** [comment]
Never mind. I see the signature of the method is different now.

**Comment by bendrucker** [comment]
I tried to keep things simple rather than trying to emulate the DOM behavior closely:

https://github.com/bendrucker/dom-event-target#caveats

For the way most people write DOM code, the ability to emit events directly for testing is pretty convenient, especially in node. `dispatchEvent` means using all the constructors plus reconstructing the event name using the constructor name and the event type. And I'm not even sure that works universally. 

I'd totally take a PR for a proper `dispatchEvent` method with plenty of tests.
